"""add vep fields and vep_jobs table

Revision ID: 06d2aca48886
Revises: 0af50254bf91
Create Date: 2026-05-29 06:36:43.214831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d2aca48886'
down_revision: Union[str, Sequence[str], None] = '0af50254bf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vep_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('vcf_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_filename', sa.String(length=255), nullable=True),
    sa.Column('input_bytes', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('status_url', sa.String(length=500), nullable=True),
    sa.Column('result_url', sa.String(length=500), nullable=True),
    sa.Column('log_url', sa.String(length=500), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vcf_file_id'], ['vcf_files.id'], name=op.f('fk_vep_jobs_vcf_file_id_vcf_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vep_jobs'))
    )
    op.create_index(op.f('ix_vep_jobs_id'), 'vep_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_vep_jobs_job_id'), 'vep_jobs', ['job_id'], unique=True)
    op.add_column('variants', sa.Column('hgvs_c', sa.String(length=255), nullable=True))
    op.add_column('variants', sa.Column('hgvs_p', sa.String(length=255), nullable=True))
    op.add_column('variants', sa.Column('consequence', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('impact', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('canonical_transcript', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('sift', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('polyphen', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('cadd', sa.Float(), nullable=True))
    op.add_column('variants', sa.Column('vep_annotated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'vep_annotated')
    op.drop_column('variants', 'cadd')
    op.drop_column('variants', 'polyphen')
    op.drop_column('variants', 'sift')
    op.drop_column('variants', 'canonical_transcript')
    op.drop_column('variants', 'impact')
    op.drop_column('variants', 'consequence')
    op.drop_column('variants', 'hgvs_p')
    op.drop_column('variants', 'hgvs_c')
    op.drop_index(op.f('ix_vep_jobs_job_id'), table_name='vep_jobs')
    op.drop_index(op.f('ix_vep_jobs_id'), table_name='vep_jobs')
    op.drop_table('vep_jobs')
    # ### end Alembic commands ###
