"""Initial migration - create all tables

Revision ID: 16d65254d9b7
Revises: 
Create Date: 2026-05-15 10:39:12.456982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d65254d9b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('ethnicity', sa.String(length=100), nullable=True),
    sa.Column('diagnosis_description', sa.Text(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('clinical_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('report_content', sa.Text(), nullable=False),
    sa.Column('report_version', sa.String(length=20), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('clinician_id', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_reports_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_reports'))
    )
    op.create_index(op.f('ix_clinical_reports_id'), 'clinical_reports', ['id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=False),
    sa.Column('hypotheses', sa.Text(), nullable=False),
    sa.Column('uncertainty_metrics', sa.JSON(), nullable=True),
    sa.Column('evidence_gaps', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_research_reports_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_reports'))
    )
    op.create_index(op.f('ix_research_reports_id'), 'research_reports', ['id'], unique=False)
    op.create_table('vcf_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_vcf_files_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vcf_files'))
    )
    op.create_index(op.f('ix_vcf_files_id'), 'vcf_files', ['id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chromosome', sa.String(length=10), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=512), nullable=False),
    sa.Column('alt', sa.String(length=512), nullable=False),
    sa.Column('variant_type', sa.String(length=50), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('filter_status', sa.String(length=50), nullable=True),
    sa.Column('info_field', sa.JSON(), nullable=True),
    sa.Column('vcf_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vcf_file_id'], ['vcf_files.id'], name=op.f('fk_variants_vcf_file_id_vcf_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variants'))
    )
    op.create_index(op.f('ix_variants_chromosome'), 'variants', ['chromosome'], unique=False)
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    op.create_index(op.f('ix_variants_position'), 'variants', ['position'], unique=False)
    op.create_index(op.f('ix_variants_variant_type'), 'variants', ['variant_type'], unique=False)
    op.create_table('acmg_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('classification_date', sa.DateTime(), nullable=False),
    sa.Column('classifier_version', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_acmg_classifications_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acmg_classifications')),
    sa.UniqueConstraint('variant_id', name=op.f('uq_acmg_classifications_variant_id'))
    )
    op.create_index(op.f('ix_acmg_classifications_classification'), 'acmg_classifications', ['classification'], unique=False)
    op.create_index(op.f('ix_acmg_classifications_id'), 'acmg_classifications', ['id'], unique=False)
    op.create_table('acmg_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=10), nullable=False),
    sa.Column('evidence_level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_source', sa.String(length=255), nullable=True),
    sa.Column('is_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], name=op.f('fk_acmg_evidence_variant_id_variants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acmg_evidence'))
    )
    op.create_index(op.f('ix_acmg_evidence_criterion'), 'acmg_evidence', ['criterion'], unique=False)
    op.create_index(op.f('ix_acmg_evidence_id'), 'acmg_evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acmg_evidence_id'), table_name='acmg_evidence')
    op.drop_index(op.f('ix_acmg_evidence_criterion'), table_name='acmg_evidence')
    op.drop_table('acmg_evidence')
    op.drop_index(op.f('ix_acmg_classifications_id'), table_name='acmg_classifications')
    op.drop_index(op.f('ix_acmg_classifications_classification'), table_name='acmg_classifications')
    op.drop_table('acmg_classifications')
    op.drop_index(op.f('ix_variants_variant_type'), table_name='variants')
    op.drop_index(op.f('ix_variants_position'), table_name='variants')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_chromosome'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_vcf_files_id'), table_name='vcf_files')
    op.drop_table('vcf_files')
    op.drop_index(op.f('ix_research_reports_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_clinical_reports_id'), table_name='clinical_reports')
    op.drop_table('clinical_reports')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
