"""add_vep_full_annotation_fields

Revision ID: 6b1564f017bb
Revises: 06d2aca48886
Create Date: 2026-05-29 11:54:26.333480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1564f017bb'
down_revision: Union[str, Sequence[str], None] = '06d2aca48886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('transcript', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('all_genes', sa.String(length=500), nullable=True))
    op.add_column('variants', sa.Column('cdna_position', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('cds_position', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('protein_position', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('amino_acids', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('codons', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('exon', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('intron', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('strand', sa.String(length=10), nullable=True))
    op.add_column('variants', sa.Column('protein_domains', sa.String(length=500), nullable=True))
    op.add_column('variants', sa.Column('revel_score', sa.Float(), nullable=True))
    op.add_column('variants', sa.Column('spliceai_ds_max', sa.Float(), nullable=True))
    op.add_column('variants', sa.Column('spliceai_type', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('loftee_lof_flag', sa.String(length=50), nullable=True))
    op.add_column('variants', sa.Column('loftee_lof_filter', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('clinvar_significance', sa.String(length=100), nullable=True))
    op.add_column('variants', sa.Column('clinvar_review_status', sa.String(length=200), nullable=True))
    op.add_column('variants', sa.Column('clinvar_star_rating', sa.Integer(), nullable=True))
    op.drop_column('variants', 'canonical_transcript')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('canonical_transcript', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('variants', 'clinvar_star_rating')
    op.drop_column('variants', 'clinvar_review_status')
    op.drop_column('variants', 'clinvar_significance')
    op.drop_column('variants', 'loftee_lof_filter')
    op.drop_column('variants', 'loftee_lof_flag')
    op.drop_column('variants', 'spliceai_type')
    op.drop_column('variants', 'spliceai_ds_max')
    op.drop_column('variants', 'revel_score')
    op.drop_column('variants', 'protein_domains')
    op.drop_column('variants', 'strand')
    op.drop_column('variants', 'intron')
    op.drop_column('variants', 'exon')
    op.drop_column('variants', 'codons')
    op.drop_column('variants', 'amino_acids')
    op.drop_column('variants', 'protein_position')
    op.drop_column('variants', 'cds_position')
    op.drop_column('variants', 'cdna_position')
    op.drop_column('variants', 'all_genes')
    op.drop_column('variants', 'transcript')
    # ### end Alembic commands ###
